### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by paradizIscool** [mopub/mopub-unity-sdk#145] opened 2020-10-13 07:25 UTC
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.14.1

#### Device model and OS Version:
Android 8, 9 reported

#### Unity Version:
2018.4.27f1

#### Steps to reproduce the behavior:
Reported on crash report tool, version deployed on 700users, reported by 5 users

#### Observed behavior:
java.util.ConcurrentModificationException
java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
java.util.HashMap$KeyIterator.next(HashMap.java:1465)
com.mopub.common.MoPubLifecycleManager.onResume(MoPubLifecycleManager.java:86)
com.mopub.common.MoPub.onResume(MoPub.java:324)
com.mopub.unity.MoPubUnityPlugin.onApplicationPause(MoPubUnityPlugin.java:351)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.c(Unknown Source:0)
com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
android.os.MessageQueue.next(MessageQueue.java:394)
android.os.Looper.loop(Looper.java:142)
com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
UnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
MoPubAndroid.OnApplicationPause (System.Boolean paused) (at <00000000000000000000000000000000>:0)

**Comment by chauduyphanvu** [comment] 2020-10-13 16:31
@paradizIscool, thanks for letting us know! I see that this is a duplicate of https://github.com/mopub/mopub-android-sdk/issues/386, for which there were no steps to reproduce the issue. 

Let us know if you could share any details about how you request and show ads. Could you paste the code you use here?

Vu Chau
MoPub Team

**Comment by paradizIscool** [comment] 2020-10-14 06:57
Banners are requested then immediately shown, auto-refresh is set, nothing more.

Interstitials and Rewarded are requested and shown on demand (by the game flow for interstitials or by the user for rewarded).
The request happened

_ after initialization
_ after shown
_ 3 sec. after an error

**Comment by paradizIscool** [comment] 2020-10-14 07:03
It happens in every case just after the start (less than 1 sec), when the application loses the focus.

**Comment by chauduyphanvu** [comment] 2020-10-15 17:17
@paradizIscool, thanks. We'll see if we can reproduce this.

**Comment by chauduyphanvu** [comment] 2020-11-06 21:02
Closing as irreproducible. Feel free to reopen if you are able to share your code.

**Closed by chauduyphanvu** 2020-11-06 21:02 UTC
