### ISSUE TITLE
Unity Android Build fails Mopub SDK 5.15

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#160] opened 2021-01-01 09:45 UTC
We have almost 30 games which were working all fine untill recently when Google admob sdk introduced <query> element in one of its manifest file. This <query> element is not part of gradle which unity used in 2018.4.30 and in unity version 2019.xxxx. Because Mopub mediation adapter for Google ads downloads files in the android folder inside plugin so it stopped all of our games to build using latest version of Mopub SDK 
We are mediating admob, FB, unity and adcolony.
We are using unity 2018.4.30. 

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.15.0
#### Device model and OS Version:
Samsung A20
#### Unity Version:
Unity on windows version 2018.4.30 and unity version 2019.xxxx
#### Ad Unit IDs used in reproducing the issue:
922479a77d064f6caf195871945c5b03
#### Steps to reproduce the behavior:
Open any WORKING unity project which has latest Mopub unity sdk in UNITY 2018.4.xxx or in unity 2019.xxx
Mediate Google admb through mopub
start GRADLE build
Build fails - Error raised is
Unknow element in manifest file <query.
We used custom gradle file as well and followed the following steps
1. downloaded gradle version 5.6.1
2. in preferences, used the above gradle version by mentioning its path
3. in build settings, selected the option to use custom gradle template, this step removed all the files from plugins-->android folder and created one file maintemplate.grade. Inside this file, we changed the version from 3.4.0 to 4.6.0.
When we generated the build, application crashed right after the start. it raised fatal exception in logcat, below is the logcat error

12-31 07:10:05.877  5626  5626 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 
12-31 07:10:05.877  5626  5626 E AndroidRuntime: ******************************************************************************
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * should follow the instructions here:                                       *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * to add a valid App ID inside the AndroidManifest.                          *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * Google Ad Manager publishers should follow instructions here:              *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: ******************************************************************************
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:7462)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7002)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6890)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:269)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2010)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7860)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
12-31 07:10:05.877  5626  5626 E AndroidRuntime: Caused by: java.lang.IllegalStateException: 
12-31 07:10:05.877  5626  5626 E AndroidRuntime: 
12-31 07:10:05.877  5626  5626 E AndroidRuntime: ******************************************************************************
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * should follow the instructions here:                                       *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * to add a valid App ID inside the AndroidManifest.                          *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * Google Ad Manager publishers should follow instructions here:              *
12-31 07:10:05.877  5626  5626 E AndroidRuntime: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *

#### Expected behavior:
Gradle build should succeed without error as it used to build before the element <query>was introduced in admob

#### Observed behavior:
Gradle build fails

**Comment by chauduyphanvu** [comment] 2021-01-03 17:21
@Cascade-Habib, this is an expected behavior from Google's AdMob SDK. It will crash your app if you do not follow its initialization requirements.

To fix this, you need to initialize AdMob with a valid app ID from your [AdMob dashboard](https://admob.google.com/home/). If you click on the link in the console log (https://developers.google.com/admob/android/quick-start#update_your_androidmanifestxml), you can see the instructions for how to include that ID in your AndroidManifest.

For Android, you can do it directly from Unity (provided that you have n AndroidManifest file). For iOS, you will need to add that ID to your info.plist in the Xcode project. Alternatively, if you can write a script for your Unity build workflow, you can dynamically insert the ID to the info.plist before Unity builds the Xcode project.

Vu Chau
MoPub Team

**Comment by Cascade-Habib** [comment] 2021-01-04 03:23
Thanks for your reply.
We never added admob app id in our manifest file by our own and EVERYTHING WAS WORKING FINE on 50+ games.Even though there was an option in PREVIOUS VERSION OF mopub manager prefab to pass admob app id.
NOW, We are using SDK manager prefab of the latest mopub sdk. in previous versions of Mopub unity SDK, you guys gave an option to pass the admop app id in MOPUB MANAGER PREFAB. 
But in latest version of mopub SDK, there is no option in mopub manager prefab to pass admob app id.
I believe there is something else which is missing.
could you please have a look one more time.
Thanks

**Comment by chauduyphanvu** [comment] 2021-01-04 16:49
@Cascade-Habib, we removed the option from the MoPubManager Prefab because it was not functional according to the way Google wanted it. Now, to initialize AdMob, you need to update your AndroidManifest and your info.plist in whichever way that works for you. 

It's possible this was not a problem for you before due to the version of the AdMob SDK used in your Unity project. And now that you might have upgraded to a newer AdMob SDK, the [initialization requirement](https://developers.mopub.com/publishers/mediation/networks/google/#update-your-androidmanifestxml-and-infoplist) now applies. That doesn't change the fact that the AdMob app ID field was present in the MoPubManager Prefab, since that field was made available by the adapters, and not the AdMob SDK.

MoPub will initialize all networks when we initialize ourselves, but if a specific ad network requires a specific piece of information in a specific way (e.g. AdMob requires it on app launch, before MoPub itself even initializes), then it's best when you handle it directly.

About the Gradle template, it looks good to me. Having `implementation 'com.mopub.mediation:[NETWORK_NAME]` will fetch the adapters, and I see that you are also fetching the mediation SDKs, so that seems fine if the actual AAR's in `plugins/android` are removed. You can always use the `implementation` directives to fetch them via Gradle.

**Comment by Cascade-Habib** [comment] 2021-01-21 13:08
Are you sure, i need to add entry in manifest file, PLEASE NOTE THAT I AM USING UNITY NOT ANDROID STUDIO.
I did not add BELOW entry in manifest BUT STILL I WAS ABLE TO SEE ADS FROM GOOGLE.
<manifest>
    <application>
        
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
    </application>
</manifest>

Could you please let me know why Google ads are being shown without above entry in manifest? i am using latest mopub sdk and adapter.

**Comment by chauduyphanvu** [comment] 2021-01-21 14:28
@Cascade-Habib, there seems to be more than 1 issues at play here.

The inclusion of the <meta-data> tag in the AndroidManifest is to satisfy the AdMob initialization requirement (otherwise, AdMob will crash the app regardless of whether it's built from Android Studio or Unity). Since you are doing that now, we can move on the next issue.

If you aren't getting ads from AdMob, do you have console logs that we can analyze? Are there any error messages? What are the ad unit IDs that you are using?

**Comment by Cascade-Habib** [comment] 2021-01-22 02:05
here is the update:
initially after upgrading latest mopub sdk, the app was crashing because of admob appid. 
But then after you suggested, we added the appid in manifest, application stopped crashing.
For testing, We again removed the Google app id from manifest and also used custom gradle like i mentioned in my previous reply, SURPRISINGLY APP IS NOT CRASHING EVEN WITHOUT ADMOB APP ID.
May be you guys have added something in adapters to add admob app id from mopub dashboard programatically, **could you please confirm?** because we are now NOT ADDING admob appid in manifest but still app is not crashing and admob ads are showing.

**Comment by Cascade-Habib** [comment] 2021-01-28 02:37
could you please reply on my previous comment.

**Comment by chauduyphanvu** [comment] 2021-01-28 15:40
@Cascade-Habib, we aren't able to comment on behaviors dictated by another mediation SDK. Please refer to [this AdMob help article](https://support.google.com/admob/answer/6232340?hl=en) on what the app ID is used for.

However, to the best of my knowledge, you must continue to have the app ID in your AndroidManifest since that requirement hasn't been changed by Google. MoPub does not handle passing/caching the AdMob app ID from our dashboard.

I see that you've opened a separate issue report for the banner sizing issue and have replied to you there.

**Comment by chauduyphanvu** [comment] 2021-02-11 22:27
It looks like we don't have any outstanding questions or issues here. I'm closing this thread now. Feel free to open a new issue if needed.

**Closed by chauduyphanvu** 2021-02-11 22:27 UTC
Labels: question
