### ISSUE TITLE
iOS build failed.

### ISSUE THREAD

**Issue by huangliulin** [mopub/mopub-unity-sdk#65] opened 2019-06-13 09:36 UTC
iOS build failed.
![image](https://user-images.githubusercontent.com/13099862/59421750-b425d300-8e01-11e9-80a8-6e67213c15b5.png)

**Comment by chauduyphanvu1** [comment] 2019-06-13 15:56
@huangliulin, could you please provide the details from [this template](https://github.com/mopub/mopub-unity-sdk/blob/master/.github/ISSUE_TEMPLATE.md) so we can have more data to help you with the issue? Specifically, what were the build steps that you took to trigger that issue?

Vu Chau
MoPub SDK Team

**Comment by chauduyphanvu** [comment] 2019-06-27 20:58
@huangliulin, do you still help with this issue? If not, feel free to close it.

**Comment by rsatrasala** [comment] 2019-07-05 20:07
Not reproducible. Closing due to inactivity.
Please open a new issue if the problem persists.

**Closed by rsatrasala** 2019-07-05 20:07 UTC
