### ISSUE TITLE
playing video ad is closed after resume from background in android device

### ISSUE THREAD

**Issue by psstevenchan** [mopub/mopub-unity-sdk#108] opened 2020-03-06 03:22 UTC
while playing video ad, background the app and resume, the video ad playback is closed on android device, but ios device will keep playing.

#### Steps to reproduce the behavior:
1. play video ad
2. in the middle of playback, background the app
3. resume the app

#### Expected behavior:
video ad is kept playing

#### Observed behavior:
video ad is closed on android device
video ad is kept playing on ios device

**Comment by chauduyphanvu** [comment] 2020-03-06 15:26
@psstevenchan, this sounds like an expected behavior due to the way Android works, but if you could provide us an ad unit ID (and the mediation networks) we could look into this further.

**Comment by chauduyphanvu** [comment] 2020-03-12 22:15
Closing as there is no repro. Feel free to reopen the issue if needed.

**Closed by chauduyphanvu** 2020-03-12 22:15 UTC
Labels: help wanted
