### ISSUE TITLE
Crash at start for AdColony?

### ISSUE THREAD

**Issue by BacheyG** [mopub/mopub-unity-sdk#127] opened 2020-06-30 10:27 UTC
````
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime ******************************************************************************
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * should follow the instructions here:                                       *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * to add a valid App ID inside the AndroidManifest.                          *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * Google Ad Manager publishers should follow instructions here:              *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime ******************************************************************************
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.app.ActivityThread.installProvider(ActivityThread.java:7278)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6813)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6699)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.app.ActivityThread.access$2000(ActivityThread.java:273)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.os.Handler.dispatchMessage(Handler.java:112)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.os.Looper.loop(Looper.java:216)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at android.app.ActivityThread.main(ActivityThread.java:7625)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at java.lang.reflect.Method.invoke(Native Method)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime Caused by: java.lang.IllegalStateException: 
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime 
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime ******************************************************************************
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * should follow the instructions here:                                       *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * to add a valid App ID inside the AndroidManifest.                          *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * Google Ad Manager publishers should follow instructions here:              *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
2020/06/30 12:19:15.933 17383 17383 Error AndroidRuntime ******************************************************************************
````
When I attempt to start my application it fatal crashes for Admob, but I did not even import Admob at all! I don't need Admob. I only imported Vungle and AdColony SDKs in the MoPub SDK manager. Should I remove those and install SDKs for each manually? Will the mediation work? I'm willing to use banner ads with AdColony and Vungle only.
Unity version:  2019.4.1.f1
Mopub SDK version: 5.13.0

Thank you!

**Comment by BacheyG** [comment] 2020-06-30 10:41
It only happens for AdColony, with Vungle only, it works well.

**Comment by chauduyphanvu** [comment] 2020-06-30 20:46
@BacheyG, based on the stack trace you provided, this issue is caused by not having a valid AdMob application ID in your AndroidManifest. Please follow the link in the stack trace (https://googlemobileadssdk.page.link/admob-android-update-manifest) for instructions on how that ID can be added to your app.

Once that is done, this crash will no longer happen. This is a known behavior with the SDK from AdMob—the link has this description:

```
Failure to add this <meta-data> tag results in a crash with the message: The Google Mobile Ads SDK was initialized incorrectly.
```

Vu Chau
MoPub Team

**Comment by BacheyG** [comment] 2020-07-14 11:05
@chauduyphanvu I do not want to use Admob, thus I do not have an id. Does Adcolony depends on Admob? In this case I won't use Adcolony.

**Comment by BacheyG** [comment] 2020-07-14 12:38
![image](https://user-images.githubusercontent.com/10908673/87426583-b0a1e400-c5df-11ea-98a4-1e41f21c7477.png)
Whenever I add the AdColony sdk, it also adds google ads dependency...

**Comment by chauduyphanvu** [comment] 2020-07-14 15:57
@BacheyG, thanks, we are able to reproduce that behavior on our end as well, and will be working on removing that AdMob dependency from the AdColony adapters. 

For now, to work around this issue, find the `AdColonyDependencies.xml` file in your Unity project, and edit it to remove the `<androidPackage spec="com.google.android.gms:play-services-ads:+"/>` entry. Then, ask the Jar Resolver / External Dependency Manager to force resolve, and rebuild your project once that's done.

We will update this thread once this issue has been resolved. Stay tuned!

**Comment by BacheyG** [comment] 2020-07-14 16:19
Thank you very much! Looking forward to your update!:)

**Comment by chauduyphanvu** [comment] 2020-07-28 13:18
@BacheyG, this issue has been addressed in https://github.com/mopub/mopub-unity-mediation/commit/78c4be858cf9aa541ffb5624b1735eae011d7393. Please update to that version and let us know if you still see the crash.

Thanks!

**Closed by chauduyphanvu** 2020-07-28 13:18 UTC
Labels: EPSO-20333
