### ISSUE TITLE
Apk can not pass Google Play

### ISSUE THREAD

**Issue by GITHUB243884919** [mopub/mopub-unity-sdk#100] opened 2020-01-08 01:39 UTC
One line summary of the issue here
Our  apk（Unity-Android） was uploaded to Google Play, then it told us the app use android.permission.ACCESS_COARSE_LOCATION. We checked our Unity project, we can not find
this. but we find it in the mopub-sdk-base.aar. In the file AndroidManifest.xml of the mopub-sdk-base.aar. it show that
uses-permission android:name="android.permission.INTERNET"
uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"
uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"
Then we removed android.permission.ACCESS_COARSE_LOCATION and builded app again.
Now your app already in the Google Play's app store.
![GP](https://user-images.githubusercontent.com/17681628/71972373-78dc6d00-3247-11ea-9c3d-f32c94e047ae.png)

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10.1
#### Device model and OS Version:
Android
#### Unity Version:
unity2018.4.2.1
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by hmertkahraman** [comment] 2020-01-08 18:50
This issue is a duplicate of [this one](https://github.com/mopub/mopub-android-mediation/issues/219).

**Closed** 2020-01-13 18:51 UTC
