### ISSUE TITLE
FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by yanmasharski** [mopub/mopub-unity-sdk#104] opened 2020-02-09 21:12 UTC
Please, switch to TryParse

FormatException: Input string was not in a correct format
System.Number.ParseSingle (System.String value, System.Globalization.NumberStyles options, System.Globalization.NumberFormatInfo numfmt) (at <00000000000000000000000000000000>:0)
MoPubManager.EmitRewardedVideoReceivedRewardEvent (System.String argsJson) (at <00000000000000000000000000000000>:0)

#### MoPub SDK Version:

MoPub 5.10

**Comment by chauduyphanvu** [comment] 2020-02-10 17:11
@yanmasharski, could you share more details on how you reproduced that Exception? Is there an ad unit ID we can try? Thanks!

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment] 2020-02-14 21:28
@yanmasharski, following up on my previous questions. Let us know if you are able to provide the data we are looking for!

**Comment by yanmasharski** [comment] 2020-02-16 14:23
I see this exceptions in Unity Cloud Diagnostics. Number of affected users 16. I can't give you any IDs.

**Comment by chauduyphanvu** [comment] 2020-02-18 19:00
@yanmasharski, it looks like this is a result of having a malformed or non-standard reward amount defined on the MoPub UI. This is code that parses the amount:

```c#
    public void EmitRewardedVideoReceivedRewardEvent(string argsJson)
    {
        var args = MoPubUtils.DecodeArgs(argsJson, min: 3);
        var adUnitId = args[0];
        var label = args[1];
        var amountStr = args[2];

        MoPubLog.Log("EmitRewardedVideoReceivedRewardEvent", MoPubLog.AdLogEvent.ShouldReward, label, amountStr);
        var evt = OnRewardedVideoReceivedRewardEvent;
        if (evt != null) evt(adUnitId, label, Single.Parse(amountStr, CultureInfo.InvariantCulture));
    }
```

With this Exception, for you `amountStr` might be something rather than a whole number between 0 999999999.  I'm curious what it could be, though, as I couldn't enter anything else:

<img width="1057" alt="Screen Shot 2020-02-18 at 1 58 57 PM" src="https://user-images.githubusercontent.com/25616035/74768606-dd331900-5256-11ea-960c-d754f3316028.png">

Are you able to look up the ad unit ID that causes that Exception to see if there's an unusual reward amount entered in? Thanks.

**Comment by aornelas** [comment] 2020-02-19 07:16
Did some testing and looks like having `" "` (space) as the value while attempting to parse yields that `Input string was not in a correct format` exception.

Not sure in which circumstances you would have a space as the reward, but guarding against this scenario to prevent the exception and log the issue...

**Comment by yanmasharski** [comment] 2020-02-19 07:17
Sorry, but I'm not allowed to give any ids.
The 99% of users don't have such exception. But it was performed for small group of users a month ago. I propose to use TryParse instead of Parse to avoid exceptions in the future.

**Comment by aornelas** [comment] 2020-02-19 07:59
Sorry, maybe I wasn't clear: we're addressing this issue in the next release. Thank you for reporting it!

**Comment by aornelas** [comment] 2020-02-20 01:59
This issue has been fixed in the latest release: https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.11.1

Thanks for reporting!

**Closed by aornelas** 2020-02-20 01:59 UTC
