### ISSUE TITLE
OverflowException: Value is greater than Char.MaxValue or less than Char.MinValue

### ISSUE THREAD

**Issue by duanzhk** [mopub/mopub-unity-sdk#69] opened 2019-07-09 10:38 UTC
Unity 5.5.6
mopub 5.7.1

OverflowException: Value is greater than Char.MaxValue or less than Char.MinValue
System.Convert.ToChar (Int32 value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Convert.cs:624)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.get_PeekChar () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:317)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.EatWhitespace () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:306)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.get_NextToken () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:345)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.ParseValue () (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:198)
MoPubInternal.ThirdParty.MiniJSON.Json+Parser.Parse (System.String jsonString) (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:122)
MoPubInternal.ThirdParty.MiniJSON.Json.Deserialize (System.String json) (at Assets/MoPub/Scripts/ThirdParty/MiniJSON.cs:89)
MoPubSDKManager+<GetSDKVersions>c__Iterator0.MoveNext () (at Assets/MoPub/Scripts/Editor/MoPubSDKManager.cs:208)
marijnz.EditorCoroutines.EditorCoroutines.MoveNext (marijnz.EditorCoroutines.EditorCoroutine coroutine) (at Assets/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:368)
marijnz.EditorCoroutines.EditorCoroutines.OnUpdate () (at Assets/MoPub/Scripts/ThirdParty/EditorCoroutines/Editor/EditorCoroutines.cs:351)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs:207)

**Comment by hmertkahraman** [comment] 2019-07-09 15:21
Hi @duanzhk,

Thanks for reporting this issue. 

Would you be able to provide a little more information for steps to reproducing it? Also can you share your Unity Editor version?

Does your SDK manager look like the following image?
<img width="995" alt="Screenshot 2019-07-09 at 11 16 04" src="https://user-images.githubusercontent.com/47573140/60900975-1fb16380-a23b-11e9-8b1b-84addc1232e2.png">

From our [initial research](https://gist.github.com/darktable/1411710/044030c6142c304f882a8f1372cd29bc8a46be6c#gistcomment-1473996), we suspect this issue can be due to internet connectivity. Can you please double check your environment can access to the url, not just in browser; possibly to ping or even curl to check the connection availability to this [url](https://mopub-mediation.firebaseio.com/.json)?

Looking forward to hear from you.

Thanks,
MoPub Team

**Comment by MochaGameStudio** [comment] 2019-07-15 09:17
> Hi @duanzhk,
> 
> Thanks for reporting this issue.
> 
> Would you be able to provide a little more information for steps to reproducing it? Also can you share your Unity Editor version?
> 
> Does your SDK manager look like the following image?
> <img alt="Screenshot 2019-07-09 at 11 16 04" width="995" src="https://user-images.githubusercontent.com/47573140/60900975-1fb16380-a23b-11e9-8b1b-84addc1232e2.png">
> 
> From our [initial research](https://gist.github.com/darktable/1411710/044030c6142c304f882a8f1372cd29bc8a46be6c#gistcomment-1473996), we suspect this issue can be due to internet connectivity. Can you please double check your environment can access to the url, not just in browser; possibly to ping or even curl to check the connection availability to this [url](https://mopub-mediation.firebaseio.com/.json)?
> 
> Looking forward to hear from you.
> 
> Thanks,
> MoPub Team

The same as I,(check this, https://github.com/mopub/mopub-unity-sdk/issues/67), I tried to ping the URL and it replay "can not find the host....". one of my workmate failed either, buy he can open the panel successfully。now he's PC become the ONLY ONE for packaging APK with mopob SDK, -_-!!!!!

**Comment by hmertkahraman** [comment] 2019-07-29 13:35
Hi @duanzhk ,

I want to check in with you on this issue; could you please let us know of the latest situation, are you able to have it work, or the problem persists? 

If so, could you please: 
- Provide more context on what sort of environment you're using, OS, Unity Version, MoPub SDK version etc.
- Ensure MoPub SDK is up to date
- Try reintegrating to your project
- Provide steps to reproduce this issue

Please let us know.

Thanks,
Mert

**Comment by sdolim** [comment] 2019-07-30 01:13
Duplicate of issue #67 -- see there for comments.

**Comment by hmertkahraman** [comment] 2019-07-31 13:48
Hi @duanzhk,

The new 5.8.0 release of the SDK guards against this now, so this issue may be fixed.
Could you please update to 5.8.0 and test if it's happening again?

Thanks,
Mert

**Comment by rsatrasala** [comment] 2019-08-16 20:25
Closing as this is a duplicate issue.

**Closed by rsatrasala** 2019-08-16 20:25 UTC
