### ISSUE TITLE
Crashes on Android - NoClassDefFoundError: Failed resolution of: Landroidx/media2/player/MediaPlayer

### ISSUE THREAD

**Issue by tontonpiero** [mopub/mopub-unity-sdk#112] opened 2020-03-26 21:49 UTC
I get lots of crashes since few days on 2 different applications when users are trying to show Mopub ads. It does'nt happened everytime. The stack trace is pretty clear but I don't know how to fix it, I already updated to the latest version of the SDK.
I need help please :)
Thanks

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.11.1

#### Device model and OS Version:
Android only. Various devices and various OS version (according to Firebase Crashlytics)

#### Unity Version:
2019.1.6f1

#### Ad Unit IDs used in reproducing the issue:
21eda876a4344e4e88072b3b65b02a9d

#### Steps to reproduce the behavior:
Display the ad.
I haven't produced it myself, I only see lots of crashes in Crashlytics since few days.

#### Expected behavior:
Don't crash

#### Observed behavior:
Crashes on many devices but not all the time

#### Evidence:
Device log files, Network log file, etc.
[stack_trace.txt](https://github.com/mopub/mopub-unity-sdk/files/4390092/stack_trace.txt)
![crash_analytics](https://user-images.githubusercontent.com/6303958/77699863-76222600-6fb3-11ea-8c9c-60e642d9c59d.png)

**Comment by dravyan** [comment] 2020-03-26 23:10
@tontonpiero, thanks for reporting. From the stack trace, it looks like the `androidx.media2.player` library being missing for your project. Please try updating the missing library and also make sure to enable the jetifier in Unity `Assets > PlayServicesResolver > Android > Force resolve`

If this does not help we will need more details such as;
- Steps to reproduce the issue
- Sample project reproducing the issue if possible.

Thanks,
Dravya 
MoPub Team

**Comment by tontonpiero** [comment] 2020-03-27 08:28
@dravyan thanks for your quick answer.

I already did a force resolve and jetifier is enable.
I also updated jar resolver to the latest.
I don't see androidx.media2.player in MopubDepencendy xml file, how can it be resolved?

I can't reproduce it myself, I only see crashes of my users.

My app was fine during weeks and it suddenly started to report lots of crashes.
Maybe it's a specific ad from the marketplace?

Thanks,
Pierre

**Comment by dravyan** [comment] 2020-03-27 22:08
@tontonpiero, thank you for the update. I have relayed this information to our internal team. We will see what we can do. I will notify this thread once we have more updates to share.

Thanks,
MoPub Team

**Comment by aornelas** [comment] 2020-03-28 02:23
We have addressed this issue in the upcoming 5.12.0 release.

In the mean time, feel free to apply the change on commit 031c832b3363a68f0f1517d3296b55abe033ad22 to our dependency file in your project.

We have also amended our release process to ensure we don't miss new dependencies in our underlying SDKs going forward. Thank you for reporting!

**Comment by chauduyphanvu** [comment] 2020-04-10 18:48
This should be fixed in the 5.12.0 SDK release. Let us know if you continue seeing the issue!

Vu Chau
MoPub Team

**Closed by chauduyphanvu** 2020-04-10 18:48 UTC
Labels: bug, workaround provided
