### ISSUE TITLE
New Banner ad size in unity sdk is not working correctly

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#94] opened 2019-11-22 02:29 UTC
I have a banner ad unity id e.x.  xxxxxx
if on scene1, i have 350X50 banner, it works and showing correctly. There is a button on Scene 1 to go to scene 2. And on Scene 2, i used the same banner ad unit id xxxxxx to show a 320X250[bigger], it still shows the same old small banner of 350X50 on scene 2.
So when the banner refreshes after say 30 seconds, the new size should apply. 

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.10
#### Unity Version:
2018
#### Steps to reproduce the behavior:
I have a banner ad unity id e.x.  xxxxxx
if on scene1, i have 350X50 banner, it works and showing correctly. There is a button on Scene 1 to go to scene 2. And on Scene 2, i used the same banner ad unit id xxxxxx to show a 320X250[bigger], it still shows the same old small banner of 350X50[even when larger ad was available].
note: i destroyed the 350X50 banner before i requested larger banner of 300X250 but still it shows smaller.
Similarly if i use larger banner on scene 1 and want to show smaller banner on scene 2 on button click of scene 1, then it still shows the larger banner instead of showing smaller banner.
Note: banner ad unit id is same which i used for samller and larger banners ... and i made sure to destroy the banner before requesting new ad size.

#### Expected behavior:
larger and bigger banner should appear

#### Observed behavior:
small banner appeared when there was larger inventory available

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment] 2019-12-09 19:16
@Cascade-Habib, are you still seeing this issue? If so, could you share with us the app you used to reproduce the issue?

For context, did you pass in the new ad size when you switch to scene 2? The load API is `MoPub.RequestBanner(bannerAdUnit, position, maxAdSize);` with `maxAdSize` being the new size you want to request for in scene 2. You will want your `maxAdSize` to be  The complete ad sizes we support are:

```
 Width300Height50
 Width300Height250
 Width320Height50
 Width336Height280
 Width468Height60
 Width728Height90
 Width970Height90
 Width970Height250
 ScreenWidthHeight50
 ScreenWidthHeight90
 ScreenWidthHeight250
 ScreenWidthHeight280
```

Vu Chau
MoPub Team

**Comment by Cascade-Habib** [comment] 2019-12-12 13:51
Yes, its still the same issue. Banner size does not refresh to new maxadsize. 
On scene 1, i requested smaller banner using MoPub.RequestBanner(bannerAdUnit, position, maxAdSize); and on scene 2, i requested bigger banner using MoPub.RequestBanner(bannerAdUnit, position, maxAdSize); yes, offcourse i used the different MaxAdSize for both requests.
I used this on three to four of my applications. All behaved the same way.

**Comment by chauduyphanvu** [comment] 2019-12-12 15:17
@Cascade-Habib, thanks for the confirmation about using different ad sizes. Could you share with us an app that reproduces that issue so we can take a look? I know that the MoPub Unity sample doesn't have more than 1 scene, but if you want to refactor it to do that, you're more than welcome to.

Thank you!

**Comment by rsatrasala** [comment] 2020-01-06 23:06
Closing due to lack of reproduction steps. Please open a new issue if you need further help.

**Closed by rsatrasala** 2020-01-06 23:06 UTC
Labels: bug
