### ISSUE TITLE
Pod install fails after updating to MoPub 5.15.0

### ISSUE THREAD

**Issue by rmohm** [mopub/mopub-unity-sdk#153] opened 2020-11-26 09:43 UTC
One line summary of the issue here

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### Device model and OS Version:
Mac mini with OS Big Sur 11.0.1

#### Steps to reproduce the behavior:
Use MoPob 5.15 and Firebase 6.16.1 in same project. MoPub 5.14 was working without errors.

#### Expected behavior:
Pod install with a result of succeeded

#### Observed behavior:

Pod install fails
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    Firebase/Analytics (= 6.32.2) was resolved to 6.32.2, which depends on
      Firebase/Core (= 6.32.2) was resolved to 6.32.2, which depends on
        FirebaseAnalytics (= 6.8.2) was resolved to 6.8.2, which depends on
          GoogleAppMeasurement (= 6.8.2)

    MoPub-AdMob-Adapters/Network (= 7.68.0.1) was resolved to 7.68.0.1, which depends on
      Google-Mobile-Ads-SDK (= 7.68.0) was resolved to 7.68.0, which depends on
        GoogleAppMeasurement (~> 7.0)

**Comment by p158276** [comment] 2020-11-27 02:42
Hi @rmohm ,
Thanks for reaching out. This issue seems related to https://github.com/mopub/mopub-ios-mediation/issues/346.
The error message shows GoogleAppMeasurement needs to be 7.0 if you use 7.68.0 Admob SDK. 

Thanks
Yoyo Lin 
MoPub Team.

**Comment by rmohm** [comment] 2020-11-27 08:20
Hi @p158276 ,
thanks for your help. Unfortunately issue "mopub/mopub-ios-mediation#346" refers to MoPub 5.14.1 and is iOS related, not Unity.

I have a project with MoPub 5.14 working without errors and after updating to MoPub 5.15 I got these errors. It seems Firebase and MoPub are not working together.... What can I do?

**Comment by p158276** [comment] 2020-11-27 08:36
Hi @rmohm , 
May I know what admob adapter version are you using in MoPub 5.14?
Can you try to build with the latest Admob adapter and Firebase Library? It seems Admob 7.68.0 SDK has a dependency on Firebase 7.0 that's why you receive this error message.

**Comment by rmohm** [comment] 2020-11-27 09:50
With MoPub 5.14 I used admob 1.5.1 adapter. 
Now with MoPub 5.15 I have admob 1.8.0 adapter (build fails).
I have latest Unity Firebase SDK 6.16.1 installed. 

Any ideas @p158276 ?

**Comment by manelizzard** [comment] 2020-12-01 10:29
We've faced same issue and manually tweaked Firebase AppDependencies.xml file with:

`Firebase/Core 7.1.0`

Maybe helps also in your scenario

**Comment by rmohm** [comment] 2020-12-02 10:02
I changed version in file "AdMopDependencies.xml" from "7.68.0.1" to "7.66.0.1". Now I can run "pod install" without problems.

**Comment by p158276** [comment] 2020-12-03 12:17
Hi @rmohm,
Just found Google has release 7.0.0 Firebase Unity package. I didn't bump to any dependency issue by using Admob adapter 1.8.0 and Firebase 7.0.0. Can you try again and let us know if you still encounter any problems?

Thanks,

Yoyo Lin
MoPub Team

**Comment by rmohm** [comment] 2020-12-03 13:13
@p158276,
with Firebase Unity 7.0.0 package pod install is working correctly.

But when building project with xcode there is another issue: In file MoPubPostBuildiOS.cs please change in "private static void PrepareProject(string buildPath)" line:

project.**Add**BuildProperty(target, "SWIFT_VERSION", "5.1");
to
project.**Set**BuildProperty(target, "SWIFT_VERSION", "5.1");

With this change I am able to build without errors...

**Comment by p158276** [comment] 2020-12-04 07:32
Hi @rmohm ,
Thanks for the follow-up.
Our sample app can be exported and run successfully with `project.AddBuildProperty(target, "SWIFT_VERSION", "5.1");`
May I know the reason for the change and also what kind of error did you encounter when you build the project?

**Comment by rmohm** [comment] 2020-12-04 08:29
Hi @p158276,
there is a "Invalid SWIFT_VERSION: Could not parse version component from '0 5'" error. I have to click on "Swift language version" and choose Swift 5 again to get project build. When using "SetBuildProperty" there is no error for me. See screenshot : https://prnt.sc/vvl4ju

**Comment by p158276** [comment] 2020-12-04 08:53
Hi @rmohm ,
Thanks for the feedback.
I checked our project again and it shows `5` instead of `5.1`. 
https://github.com/mopub/mopub-unity-sdk/blob/4af137ce1fdb60845b99ecad4204faa568ccd483/unity-sample-app/Assets/MoPub/Scripts/Editor/MoPubPostBuildiOS.cs#L45

This shouldn't have a problem when export and build the iOS package.
Please feel free to let us know if you have any questions.

**Comment by p158276** [comment] 2020-12-21 08:33
Hi @rmohm ,
We've tried to reproduce the same issue by setting the version to 5.1. But the configure seems fine on my end. 
This might be an issue with the post-build process not being able to match "5" with "5.0" as the same swift version.
Unfortunately, we cannot determine which 3rd party might be causing the issue in our environment but appreciate it if you can share feedback with us.

**Comment by agrobost** [comment] 2021-01-04 23:58
https://github.com/mopub/mopub-unity-sdk/issues/161#issuecomment-754292980

**Comment by p158276** [comment] 2021-02-17 07:41
Fixed in v[5.16.0](https://github.com/mopub/mopub-unity-sdk/commit/ee33ae47a05bc2677262cf87673dd3a6fed37d81#diff-e8b711a273c4b593e3c5b248afb5c53068b38faf006d861d8ab6f6268105b6bcR49). Let us know if you continue seeing the issue!

**Closed** 2021-02-25 20:55 UTC
