### ISSUE TITLE
Banner Ads & medium Rectangle taking full screen width

### ISSUE THREAD

**Issue by Cascade-Habib** [mopub/mopub-unity-sdk#165] opened 2021-01-28 03:35 UTC
One line summary of the issue here

After upgrading to latest mopub unity sdk, Banner Ads & medium Rectangle taking full screen width.

#### MoPub SDK Version:
5.15
#### Device model and OS Version:
Samsung A21 , Latest Android version
#### Unity Version:
2018.4.30
#### Ad Unit IDs used in reproducing the issue:
01a7eb6b22df47e4accb5c167fcc5663
#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
1. Facebook medium rectangle of 300X250[on mopub UI] is showing on phone screen covering full screen width and looks like FullScreenWidth X 250 instead of 300 X 250. Admob banner in Medium rectangle however shows properly that is.. 200 X 250
2. Facebook Banner of size 320X50[on Mopub UI] is showing on phone screen as FullScreenWdith X 50 instead of 320X50. However admob banner appears properly that is 350 X 50
3. Admob Banner shows correctly, but it does not RE-APPEAR AFTER REFRESH INTERVAL, so it only appears once for few seconds and then disappears and never appear again
#### Expected behavior:
As concisely as possible, describe the expected behavior.
banner ads should appear as per the defined 300X50 size 
medium rectangle should appear as per the defined 300X250 size
admob banner should keep showing untill user is playing the game
#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment] 2021-01-28 15:31
@Cascade-Habib, could you confirm the MoPub ad size constant you are using to make your ad request? Do you also have screenshots to corroborate this issue?

Thank you!

Vu Chau
MoPub Team

**Comment by Cascade-Habib** [comment] 2021-01-29 02:34
sure, i have verified ad sizes many times. Please see the screenshots of AD SIZES on MOPUB UI.
Also, please see the attached screenshots of the ads which appear on mobile in wrong sizes
![Banner](https://user-images.githubusercontent.com/17279298/106224031-53c8ec80-6204-11eb-90e1-dc583a354f0e.jpg)
![MediumRectangle](https://user-images.githubusercontent.com/17279298/106224037-56c3dd00-6204-11eb-8a02-d9b3ea8bfb9c.jpg)

**Comment by chauduyphanvu** [comment] 2021-02-02 17:15
@Cascade-Habib, thanks for the confirmation!

When is this issue happening? Do you see it when requesting ads in landscape orientation only?

**Comment by Cascade-Habib** [comment] 2021-02-08 03:36
i tested it only on landscape mode.

**Comment by chauduyphanvu** [comment] 2021-02-08 15:17
Thanks, @Cascade-Habib. We tested a few scenarios in our sample app but weren't able to reproduce this behavior. 

Is there any chance you could share with us a mini version of your Unity project that reproduces that issue? What is the specific device that you are seeing this issue on (resolution/screen density)? Thanks!

**Comment by Cascade-Habib** [comment] 2021-02-09 00:52
did you test ONLY MOPUB MARKETPLACE banners?
or did you test admob and FAN banners aswell through mopub mediation?

**Comment by chauduyphanvu** [comment] 2021-02-09 00:53
@Cascade-Habib, we tested with both Marketplace and mediated banners. How did you reproduce the issue?

**Comment by Cascade-Habib** [comment] 2021-02-09 02:50
could you please post the android manifest file you used for admob and FAN banner testing through mediation?
regarding how we reproduced the issue:
We upgraded from 5.15 to latest mopub SDK and used custom gradle file because we are using unity 2018.4.30. due to <query< element unity build fails so we used custom gradle file, i am attaching it here , may be there is some problem using custom gradle file or in our androidmanifest.
here are the two files
1. Android manifest file
[AndroidManifest.txt](https://github.com/mopub/mopub-unity-sdk/files/5948407/AndroidManifest.txt)
2. custom gradle file
[mainTemplate.txt](https://github.com/mopub/mopub-unity-sdk/files/5948414/mainTemplate.txt)

**Comment by chauduyphanvu** [comment] 2021-02-11 21:57
@Cascade-Habib, we use the sample app hosted on this repo, so the AndroidManifest can be found [here](https://github.com/mopub/mopub-unity-sdk/blob/master/unity-sample-app/Assets/Plugins/Android/AndroidManifest.xml). 

Having said that, having a custom Gradle should not affect your ad serving experience. 

Are you able to share with us a small sample project that reproduces the issue?

**Comment by Cascade-Habib** [comment] 2021-02-13 02:21
Could you please send me the manifest file which you used during mediation testing for admob and FAN?
the link you sent in your previous comments, does not have entries for admob and FAN.
I think sample app does not show mediated networks and so it does not have entries in  manifest file for mediated networks.
 if you could point me to full functional demo where i can see admob and FAN banners working correctly then that would be great.

**Comment by Cascade-Habib** [comment] 2021-02-16 02:04
could you please reply my previous comment?

**Comment by wacamoe** [comment] 2021-02-17 17:25
@Cascade-Habib thank you for continuing to troubleshoot. As @chauduyphanvu states, having a reproducible project will help immensely. We do not publish our mediation sample app for Unity, however, you can get the Native version of the sample app from the Google Play store [here](https://play.google.com/store/apps/details?id=com.mopub.simpleadsdemo)

Currently, we are unable to reproduce your issue. If you wish to use our Unity sample app to recreate a mini reproducible of the issue you are encountering,  could you compile it locally on your machine by checking out the code in the repo itself? If you can reproduce it in the sample app, then we can continue to debug further for the issue you are reporting. We cannot ascertain if this is local to your specific setup, or something deeper that we can dig into.

**Comment by Cascade-Habib** [comment] 2021-02-17 17:25
Here is the sample project you requested
https://www.dropbox.com/s/8vpfyftw9i9e3ly/unity-sample-app.zip?dl=0

remember, there are two issues
1. Admob banner will show, but it will never refresh after refresh interval and will disappear automatically and will never show again
2. Facebook medium rectangle takes up full screenwidth istead of the size mentioned in the code and in the Mopub UI

**Comment by chauduyphanvu** [comment] 2021-02-19 17:02
@Cascade-Habib, thanks for sharing your project. We'll take a look and let you know what we find.

> Admob banner will show, but it will never refresh after refresh interval and will disappear automatically and will never show again

This issue doesn't sound similar to what we've been discussing on this thread. Could you start a new issue report for it? Thank you!

**Comment by chauduyphanvu** [comment] 2021-02-19 18:23
@Cascade-Habib - your project needs the NDK and I can't quite get it up and running yet. Do you have a project without a dependency on the NDK?

**Comment by Cascade-Habib** [comment] 2021-02-20 03:12
@chauduyphanvu - in "build settings" under "other settings" change the option"Scripting Background" to Mono.
It will not require NDK.

**Comment by Cascade-Habib** [comment] 2021-02-25 01:56
any update on this please?

**Comment by chauduyphanvu** [comment] 2021-02-25 16:01
@Cascade-Habib, thanks for checking in. I've reproduced something similar for Facebook banners. I'll investigate and get back with an update!

**Comment by Cascade-Habib** [comment] 2021-03-02 16:53
any solution for this please?

**Comment by chauduyphanvu** [comment] 2021-03-04 14:05
@Cascade-Habib, the team is still investigating the issue. I will update this thread once I have more information. Stay tuned!

**Comment by Cascade-Habib** [comment] 2021-03-07 07:08
We have more than 100 Games, and all of them need an urgent update.
We have been facing this issue since two months on more than 100 games, Our revenue loss is more than $50,000 because of this issue.
Is it our mistake that we chose mopub?
Could you please give us a solution as soon as possible.

**Comment by chauduyphanvu** [comment] 2021-03-09 16:59
@Cascade-Habib, we've identified the cause of the issue and fixed it internally. If all looks good, the fix should be shipped with the upcoming SDK release. When there's more information, I will make sure to keep you updated.

Thanks!

**Comment by Cascade-Habib** [comment] 2021-03-16 02:09
any update please?

**Comment by chauduyphanvu** [comment] 2021-03-16 23:37
@Cascade-Habib, we are planning to release the new SDK some time this week. I will update the thread once it is available.

**Comment by chauduyphanvu** [comment] 2021-03-19 16:21
@Cascade-Habib, 5.16.2 is released now and it contains a fix for this issue. Give it a try and let us know if you continue seeing the issue!

**Comment by Cascade-Habib** [comment] 2021-03-27 01:15
sure, i will try it.
one question.
We are using mediation and we are using Mopub manager prefab. 
Does this prefab autoinitializes admob, facebook, unity and adcolony sdk's itself? 
or do we need to initialize these network sdks before initializing mopub manager?

**Comment by chauduyphanvu** [comment] 2021-03-29 15:48
@Cascade-Habib, since this is a new issue, could you open a new issue thread? We should then be able to help with your new questions.

Thanks.

**Closed by chauduyphanvu** 2021-03-29 15:48 UTC
Labels: ADF-5729

**Comment by chauduyphanvu** [comment] 2021-03-30 20:38
@Cascade-Habib, I'm trying with the ad unit ID 01a7eb6b22df47e4accb5c167fcc5663 from you and I'm always getting ads matching the size I specify. Do you have screenshots or logs that describe the issue?

**Comment by Cascade-Habib** [comment] 2021-04-10 10:18
yes you are right. it has been fixed now.
Thanks
