### ISSUE TITLE
Wrong signature of using setting LogLevel for Android

### ISSUE THREAD

**Issue by firatagdas** [mopub/mopub-unity-sdk#167] opened 2021-02-08 09:05 UTC
https://github.com/mopub/mopub-unity-sdk/blob/4af137ce1fdb60845b99ecad4204faa568ccd483/unity-sample-app/Assets/MoPub/Scripts/Internal/MoPubAndroid.cs#L90

This should be

```
PluginClass.CallStatic("setLogLevel", (int) value);
```

**Comment by hmertkahraman** [comment] 2021-02-09 13:35
Hi @firatagdas ,

We're using [C# properties](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/using-properties) to define the setter, and generics to declare the return type. We would very much appreciate if you could explain the reasoning behind on this?

Thanks,
MoPub Team

**Comment by firatagdas** [comment] 2021-02-09 13:40
Sure, 

There is no mistake in syntax. However, the underlying Java method return type is void. So getting LogLevel via C# Property is fine. But setting throws an exception. You can test this simply by just setting a LogLevel value on real Android device.

https://github.com/mopub/mopub-unity-sdk/blob/master/mopub-android-sdk-unity/src/main/java/com/mopub/unity/MoPubUnityPlugin.java#L280

**Comment by hmertkahraman** [comment] 2021-02-09 19:34
Hi @firatagdas ,

Well received and confirmed. We will be fixing this. Will update here once this is shipped on a future SDK release.

Thanks for reporting.

Mert

**Comment by wacamoe** [comment] 2021-02-17 17:50
Hi @firatagdas - This has been addressed in the [5.16.0](https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.16.0) release. Thank you again for your report.

**Closed by wacamoe** 2021-02-17 17:50 UTC
