### ISSUE TITLE
【Android Error】In LoadInterstitial It's time to crash

### ISSUE THREAD

**Issue by DeleAngle** [mopub/mopub-unity-sdk#136] opened 2020-08-07 14:34 UTC
Cause MoPub.LoadInterstitialPluginsForAdUnits() crash on

#### Steps to reproduce the behavior:
1、Call MoPub.LoadInterstitialPluginsForAdUnits()

#### Expected behavior:
Load InterstitialAd

#### Observed behavior:
Game crash

#### Evidence:
2020-08-07 22:26:54.979 20058-20058/com.bello.shootingworld2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bello.shootingworld2, PID: 20058
    java.lang.Error: FATAL EXCEPTION [main]
    Unity version     : 2018.4.18f1
    Device model      : motorola Nexus 6
    Device fingerprint: google/shamu/shamu:7.1.1/N6F26Q/3549652:user/release-keys
    
    Caused by: java.lang.AbstractMethodError: abstract method "void com.mopub.mobileads.MoPubAd.setAdUnitId(java.lang.String)"
        at com.mopub.mobileads.MoPubInterstitial.<init>(MoPubInterstitial.java:90)
        at com.mopub.unity.MoPubInterstitialUnityPlugin$1.run(MoPubInterstitialUnityPlugin.java:56)
        at com.mopub.unity.MoPubUnityPlugin$10.run(MoPubUnityPlugin.java:541)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by hmertkahraman** [comment] 2020-08-10 12:51
Hi @DeleAngle ,

Thanks for reaching out. We're investigating the issue and will get back to you.

Thanks,
Mert

**Comment by p158276** [comment] 2020-08-19 06:01
Hi @DeleAngle ,

Thanks for waiting. We are not able to reproduce the same problem in [our sample app](https://github.com/mopub/mopub-android-sdk/tree/master/mopub-sample)  when loading the interstitial Ad with 2018.4.18f1.
Could you attach a reproducible sample app to this report? 
We’ll take a look and get back to you.

Yoyo Lin,
MoPub Team

**Comment by DeleAngle** [comment] 2020-08-19 06:04
thank you. I rolled back the mopub version to 5.12.0, and it seemed normal.

I think it should be the problem of dependency library

**Comment by DeleAngle** [comment] 2020-08-19 06:05
So we've discarded the version that went wrong

**Comment by sanderson82** [comment] 2020-08-20 19:10
I am seeing the same issue with Unity and Android.  I do not see the issue in my pure android implementation.

This issue looks similar to https://github.com/mopub/mopub-android-sdk/issues/415

The class MoPubAds uses the annotation @JvmDefault to define default methods:
https://github.com/mopub/mopub-android-sdk/blob/90521b9ce0b8ea7293ab0cbe6c13c04b55905a79/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/MoPubAd.kt

and then in 
https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sdk/shared-build.gradle#L27
you can see this being set "-Xjvm-default=enable"

From the documentation:
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/-jvm-default/#:~:text=Specifies%20that%20a%20JVM%20default,non%2Dabstract%20Kotlin%20interface%20member.&text=In%20this%20mode%2C%20annotating%20an,method%20from%20the%20DefaultImpls%20class.

"with -Xjvm-default=enable, only default method in interface is generated for each @JvmDefault method. In this mode, annotating an existing method with @JvmDefault can break binary compatibility, because it will effectively remove the method from the DefaultImpls class."

I am guessing there is some incompatibility in the way the methods are generated and how the projects are configured. 
I have an exported Unity project that exhibits this issue that I can share privately if that helps, just let me know where to share it.

**Comment by wacamoe** [comment] 2020-08-20 19:24
@sanderson82 if you can share the repro project (assuming its a minimal use case and not confidential) that would be great!

**Comment by sanderson82** [comment] 2020-08-20 19:29
Try:  https://drive.google.com/file/d/1zDaAoAKQsA1YyS9xWA3gfSPlxbcRI11N/view?usp=sharing

The crash happens only on loading interstitial.

**Comment by wacamoe** [comment] 2020-08-20 21:59
@sanderson82 thanks - we also upgraded our sample app internally and after some tinkering with EDM got out an APK that reproduces. We're investigating now.

**Comment by wacamoe** [comment] 2020-08-25 20:06
> @wacamoe
> Try: https://drive.google.com/file/d/1zDaAoAKQsA1YyS9xWA3gfSPlxbcRI11N/view?usp=sharing
> 
> The crash happens only on loading interstitial.

Hey @sanderson82 - do you have the unity project vs the exported gradle project? We think we may have some settings that might have to go at the Unity level to address without an SDK update, but want to confirm.

**Comment by sanderson82** [comment] 2020-08-25 20:28
https://drive.google.com/file/d/1Dy4-OFyApI0QpnUs6GK7hC_yYIG_kpgR/view?usp=sharing

Make sure you keep the android dependencies unchanged since the HyprMX
MoPub one is the one we are currently developing.

Let me know if you need anything else.

**Comment by DeleAngle** [comment] 2020-08-26 14:29
[build.gradle.txt](https://github.com/mopub/mopub-unity-sdk/files/5130456/build.gradle.txt)
I can only provide gradle, which is currently using 5.12.0

**Comment by chauduyphanvu** [comment] 2020-08-27 15:41
Hi all,

We have fixed this issue internally and will release the fix with the upcoming SDK. In the meantime, we have identified a workaround—feel free to give it a try and let us know if you still see the crash.

After integrating the MoPub Unity SDK, do the following:
* Delete all AARs from Assets/MoPub/Plugins/Android except mopub-unity-wrappers.*
* Delete Assets/MoPub/Plugins/Android/MoPub.plugin/libs/mopub-volley-2.0.0.*
* Add to Assets/MoPub/Scripts/Editor/MoPubDependencies.xml:
    * Above the line `</androidPackages>` add `<androidPackage spec="com.mopub:mopub-sdk:5.13.1"/>`
* Ensure that your application has multidex enabled
* Ensure that your application has androidX enabled
* Build and run your Unity project as usual

Reminder to remove the workaround when updating to the upcoming SDK version.

Vu Chau
MoPub Team

**Comment by aornelas** [comment] 2020-08-27 16:03
Thanks, Vu!

Quick clarification: the workaround above is the same as the fix that will be released, so no need to revert anything when updating.

**Comment by SelcukSZR** [comment] 2020-10-08 04:44
Same problem still occurs on 5.14.1 SDK.

**Comment by aornelas** [comment] 2020-10-08 05:55
To address this issue (even after upgrading to `5.14.1`), please follow [Vu's recommended steps above](https://github.com/mopub/mopub-unity-sdk/issues/136#issuecomment-682028743) and ensure you have `android.enableDexingArtifactTransform=false` in your gradle properties (see [our README](https://github.com/mopub/mopub-unity-sdk#additional-requirements-for-unity-2020) for more details).

**Closed by aornelas** 2020-10-08 05:55 UTC
Labels: ADF-5292, bug

**Comment by SelcukSZR** [comment] 2020-10-08 06:11
Jetifier is already enabled so androidx is, do we have to use custom gradle temple to use the sdk from now on?

**Comment by aornelas** [comment] 2020-10-08 06:57
You should only need the custom gradle properties to enable `useAndroidX` and disable `enableDexingArtifactTransform`.

**Comment by SelcukSZR** [comment] 2020-10-08 07:16
Thank you, I will give it a try.
