### ISSUE TITLE
NSInvalidArgumentException: Application tried to present modally an active controller

### ISSUE THREAD

**Issue by JimmyDeemo** [mopub/mopub-unity-sdk#48] opened 2019-03-19 13:32 UTC
iOS App crashes under certain conditions when trying to show the consent dialogue.

- [*] I am submitting a bug report for existing functionality
- [*] I visited https://developers.mopub.com/ and found no answer
- [*] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [*] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Invoke the GDPR consent dialogue under certain (undetermined) conditions.

#### Expected behavior:
GDPR consent screen should be displayed until a user opts in or out. It should then close.

#### Observed behavior:
Application crashes while loading the consent screen. In some instances a white screen is shown (consent screen background) briefly before crashing, others the text displays for a second before crashing.

#### Evidence:
Exception:

> MoPubManager:EmitConsentDialogLoadedEvent()
> 2019-03-18 16:39:36.278840+0000 myapp[3072:9335805] Uncaught exception: NSInvalidArgumentException: Application tried to present modally an active controller <UnityDefaultViewController: 0x11f51fa60>.
> (
> 	0   CoreFoundation                      0x0000000184836da4 <redacted> + 252
> 	1   libobjc.A.dylib                     0x00000001839f05ec objc_exception_throw + 56
> 	2   UIKit                               0x000000018e67aac8 <redacted> + 4812
> 	3   UIKit                               0x000000018e8f33a0 <redacted> + 104
> 	4   UIKit                               0x000000018e6313e4 <redacted> + 512
> 	5   UIKit                               0x000000018e6797bc <redacted> + 180
> 	6   UIKit                               0x000000018e679654 <redacted> + 160
> 	7   myapp                          0x00000001014184cc -[MPConsentManager showConsentDialogFromViewController:didShow:didDismiss:] + 368
> 	8   myapp                          0x0000000101493174 -[MoPub(Consent) showConsentDialogFromViewController:didShow:didDismiss:] + 188
> 	9   myapp                          0x0000000101493234 -[MoPub(Consent) showConsentDialogFromViewController:completion:] + 112
> 	10  myapp                          0x00000001012ac5a8 _moPubShowConsentDialog + 140
> 	11  myapp                          0x000000010304ce04 MoPubiOS__moPubShowConsentDialog_m3561530284 + 24
> 	12  myapp                          0x000000010304cde0 MoPubiOS_ShowConsentDialog_m1932377539 + 336
> 	13  myapp                          0x0000000102ae3fdc AdvertManager_OnConsentDialogLoadedEvent_m587783966 + 456
> 	14  myapp                          0x0000000104be692c Action_Invoke_m937035532 + 412
> 	15  myapp                          0x00000001030537ec MoPubManager_EmitConsentDialogLoadedEvent_m1376776774 + 332
> 	16  myapp                          0x00000001011641f8 _Z31RuntimeInvoker_Void_t1185182177PFvvEPK10MethodInfoPvPS4_ + 60
> 	17  myapp                          0x00000001025067b4 _ZN6il2cpp2vm7Runtime6InvokeEPK10MethodInfoPvPS5_PP15Il2CppException + 68
> 	18  myapp                          0x0000000101d0c5a0 _Z23scripting_method_invoke18ScriptingMethodPtr18ScriptingObjectPtrR18ScriptingArgumentsP21ScriptingExceptionPtrb + 100
> 	19  myapp                          0x0000000101d148e8 _ZN19ScriptingInvocation6InvokeEP21ScriptingExceptionPtrb + 60
> 	20  myapp                          0x0000000101d19f44 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtrP21ScriptingExceptionPtr + 1180
> 	21  myapp                          0x0000000101d1a140 _ZN13MonoBehaviour30InvokeMethodOrCoroutineCheckedE18ScriptingMethodPtr18ScriptingObjectPtr + 84
> 	22  myapp                          0x0000000101d10b68 _ZN9Scripting20SendScriptingMessageER10GameObjectPKc18ScriptingObjectPtr + 260
> 	23  myapp                          0x000000010206c164 _ZN12WebScripting19ProcessSendMessagesEv + 160
> 	24  myapp                          0x0000000101c33aa4 _Z10PlayerLoopv + 1204
> 	25  myapp                          0x0000000101a28f48 _ZL19UnityPlayerLoopImplb + 36
> 	26  myapp                          0x00000001006b76a4 UnityRepaint + 64
> 	27  myapp                          0x00000001006b7658 -[UnityAppController(Rendering) repaint] + 96
> 	28  myapp                          0x00000001006b75a0 -[UnityAppController(Rendering) repaintDisplayLink] + 112
> 	29  GPUToolsCore                        0x00000001109c05f0 -[DYDisplayLinkInterposer forwardDisplayLinkCallback:] + 176
> 	30  QuartzCore                          0x00000001888a8f4c <redacted> + 820
> 	31  IOKit                               0x0000000184a9f48c IODispatchCalloutFromCFMessage + 492
> 	32  CoreFoundation                      0x00000001847c4b20 <redacted> + 188
> 	33  CoreFoundation                      0x00000001847dfae8 <redacted> + 56
> 	34  CoreFoundation                      0x00000001847df230 <redacted> + 440
> 	35  CoreFoundation                      0x00000001847dcc80 <redacted> + 2456
> 	36  CoreFoundation                      0x00000001846fcda8 CFRunLoopRunSpecific + 552
> 	37  GraphicsServices                    0x00000001866e2020 GSEventRunModal + 100
> 	38  UIKit                               0x000000018e71c758 UIApplicationMain + 236
> 	39  myapp                          0x00000001006a9954 main + 212
> 	40  libdyld.dylib                       0x000000018418dfc0 <redacted> + 4
> )

Under most conditions this dialogue seems to present without error. I am looking for help determining what other actions happening at the time might cause this exception.

**Comment by chauduyphanvu1** [comment] 2019-03-20 19:42
JimmyDeemo - thanks for letting us know! Do you tend to see more of this crash on specific setups (device form factors, etc.) versus others? Do you see it in our Unity sample app?  If not, could you send us the build you are using?

We'll debug this and post an update if we identify the root cause of the crash.

Vu Chau
MoPub SDK Team

**Comment by JimmyDeemo** [comment] 2019-03-21 09:24
@chauduyphanvu1 Unfortunately I don't have much more information for you.

> Do you tend to see more of this crash on specific setups (device form factors, etc.) versus others?
Not that we are aware of, we have repro steps for our project, and they seem to repro on any iOS device. It is considered a rare crash for us, as the steps we have are convoluted for our signup/login process.

> Do you see it in our Unity sample app? If not, could you send us the build you are using?
Sorry but due to my other workload I have been unable to investigate this further. It actually reproduces in our live build, but would you need a debug build? I'll try to see if we can get a version over to you through our MoPub contact; I wanted to post here for viability and perhaps more insight into the cause.

**Comment by chauduyphanvu1** [comment] 2019-03-22 13:39
@JimmyDeemo, thank you. We added a guard against this in the iOS SDK, and the fix should be released in the upcoming iOS and Unity SDK. 

On a related note, is there any possibility you are unknowingly making multiple calls to loading and showing the consent dialog?

**Closed** 2019-05-11 00:15 UTC
Labels: bug
